sqlite: &sqlite
  adapter: sqlite3
  database: db/development.sqlite3

mysql: &mysql
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  database: test

pg: &pg
  adapter: postgresql
  host: 192.168.59.103
  username: postgres
  password: password
  encoding: unicode

development:
  <<: *mysql

test:
  <<: *sqlite
  database: db/test.sqlite3
